virajmahesh/icsi-shift-scheduler

features/create_event.feature
Write Cucumber tests for create/delete/editing event features
=> Write Cucumber tests for create/delete/editing event features

features/future_events_view.feature, features/shifts_view.feature
view all future events and different shifts of an event
=> Luba views events and shifts

.gitignore, .travis.yml, config/cucumber.yml, features/create_event.feature, features/create_shift.feature, features/future_events_view.feature, features/join-shift.feature, features/leave-shift.feature, features/login.feature, features/notify_join.feature, features/notify_leave.feature, features/shift_limit_user.feature, features/shifts_view.feature, features/signup.feature, features/step_definitions/custom_steps.rb, features/view_filled_shifts.feature
Travis CI build is now passing
=> Reformat test code and mark tests as pending

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/user_controller.rb, app/models/user.rb, app/views/application/index.html.erb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/user/new.html.erb, config/.codeclimate.yml, config/routes.rb, db/migrate/20160306211058_rename_password_to_password_digest.rb, db/schema.rb, features/login.feature, features/signup.feature, features/step_definitions/custom_steps.rb, features/support/paths.rb, spec/controllers/sessions_controller_spec.rb, spec/models/user_spec.rb, spec/support/factory_girl.rb
Implement signup so that users can create accounts
Implement login so that users that created accounts can login to their account
Update tests so that syntax matches steps in web_steps.rb
Add more tests to ensure correct login and signup behavior
Migrate the database to password_digest insted of plain text passwords
=> Implement signup and login

app/controllers/shifts_controller.rb, app/models/shift.rb, app/views/events/show.html.erb, features/create_event.feature, features/create_shift.feature, features/join_shift.feature, features/leave_shift.feature, features/login.feature, features/shift_limit_user.feature, features/shifts_view.feature, features/signup.feature, features/step_definitions/custom_steps.rb, features/step_definitions/web_steps.rb, features/support/paths.rb, features/view_future_events.feature
Refactor tests to reuse common steps defined in custom_steps.rb. Delete duplicate steps.
Make tests easier to understand, with the side effect of making them more verbose.
=> Refactor tests

.travis.yml, config/database.travis.yml
Run tests using PostgreSQL in Travis CI, since PostgreSQL is our production DB.
=> Run tests using PostgreSQL in Travis CI

features/create_shift.feature
event description box should have multiple lines.
=> event_description_box

app/controllers/application_controller.rb, app/controllers/events_controller.rb, app/controllers/shifts_controller.rb, app/controllers/users_controller.rb, app/models/ability.rb, app/views/events/show.html.erb, features/create_event.feature, spec/controllers/events_controller_spec.rb
Add tests that verify:
- Users must be logged in to create an event
- Only the event creator can update or delete and event
=> Prevent unauthorized users from modifying an event

app/models/shift.rb, app/views/events/edit.html.erb, app/views/events/new.html.erb, app/views/shifts/edit.html.erb, app/views/shifts/new.html.erb, features/create_event.feature, features/create_shift.feature, features/step_definitions/custom_steps.rb
Use a date and time picker to select dates and times so that inputs are better formatted. Update cucumber steps so that they can handle the new date and time pickers.
=> Input dates and times in a better ways

app/models/shift.rb, app/views/events/show.html.erb, app/views/shifts/show.html.erb, features/create_event.feature, features/create_shift.feature
Clean up the shift view so that shift information is on seperate lines
=> Clean up the shift view

app/models/event.rb, db/seeds.rb
Create sample users, events and shifts so that this information is available at deploy time
=> Seed the DB with information for testing

app/controllers/shifts_controller.rb, app/models/event.rb, app/models/shift.rb, app/views/shifts/new.html.erb, app/views/shifts/show.html.erb, features/create_event.feature, features/create_shift.feature, features/join_shift.feature, features/leave_shift.feature, features/number_users_for_event.feature, features/shift_description.feature, features/shift_limit_user.feature, features/shifts_view.feature, features/step_definitions/custom_steps.rb, spec/controllers/events_controller_spec.rb
create event and shift features should pass all the tests
=> Nava shift event debug

Gemfile, Gemfile.lock, app/controllers/roles_controller.rb, config/routes.rb
get /autocomplete/:text returns array of roles ordered by similarity.
=> Created roles ranking API

app/controllers/shifts_controller.rb, app/views/shifts/edit.html.erb, app/views/shifts/new.html.erb, app/views/shifts/show.html.erb, db/migrate/20160331072202_add_description_to_shifts.rb, db/schema.rb, features/shift_description.feature, features/step_definitions/custom_steps.rb
=> Kalon shift description

app/views/shifts/edit.html.erb, app/views/shifts/show.html.erb, db/schema.rb
- Fix broken "Back to Event" link in shift edit.html.erb
- Fix broken "Add Shift" link in shift show.html.erb
=> Fix broken links in shift views

features/event_shift_notifications.feature
Added tests for a notification 24 hours before an event
Added tests for a notification 24 hours before a shift
=> Added 24 hour notification tests

app/controllers/users_controller.rb, app/models/volunteer_commitment.rb
Moved all creating notification code to users controller
=> Fixed notifications nil error

Procfile
Fixed "max number of clients reached" error
=> Fixed Max Client Error

features/user_activity.feature
Added tests for dismissing/deleting notifications
=> Add tests for deleting nofications

app/controllers/shifts_controller.rb, app/models/event.rb, app/models/shift.rb, app/models/user_activities/remove_user_activity.rb
When removing a user from a shift, the removed user will see a notification saying s/he has been removed.
=> Generate notification when removing user from shift

app/assets/javascripts/application.js, app/controllers/events_controller.rb, app/views/events/edit.html.erb, app/views/events/new.html.erb, app/views/events/shared/_create_edit_event.html.erb, features/create_event.feature
- Edit event should use the event date as the starting date
- Edit event should allow you to edit the time
- Edit event should use a large text box for description
=> Fix inconsistency with edit event view

app/controllers/events_controller.rb, app/controllers/users_controller.rb, app/jobs/event_notification_job.rb, app/models/user_activities/event_create_activity.rb, app/models/user_activities/user_join_activity.rb, app/models/user_activities/user_leave_activity.rb, features/user_activity.feature
Added the following notifications to notification feed:
-User receives notification when they leave a shift.
-User receives notification when they join a shift.
-Event Creator receives notification when they create an event.
=> Add the additional notifications Madelaine requested

app/controllers/events_controller.rb, features/event_shift_notifications.feature, features/user_activity.feature
When copying events, generate the notification for creating an event and schedule event reminder notification.
=> Add notifications to copied events

app/controllers/users_controller.rb
Shift reminder notifications are now created 1 day before the event time.
=> Shift reminder notifications are now created 24 hours before event date

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
=> Prevent users for signing up twice for the same shift
